### ISSUE TITLE
VoiceCallBack Status issue

### ISSUE THREAD

**Issue by girubhai** [twilio/voice-quickstart-server-node#16]
When Callee has no internet and caller place call, ringing volume play on caller side and at server Status CallBack Request following status flow occur :

1.Initiated 2. Ringing 3. no-answer

So the question is why Ringing callback status occur while callee has not network  connection.

**Comment by bobiechen-twilio** [comment]
Hi @girubhai 

Thanks for reaching out.
The caller client will receive the ringing callback even if the callee is not reachable. Twilio will try to send out call invites (for mobile clients they will be in the form of push notifications) and provide a ringing callback to the caller when the call connection between the caller and Twilio is established.

**Comment by girubhai** [comment]
Hi @bchen-twilio Thanks to reply.
One more question,
As I think twilio send push notification to callee to answer call. And when callee is offline then there will be no push and twilio can verifiy in push callback that push was not sent.
Therefore twilio server can send status callback as calling until push notification result and once push send, server can send status callback as Ringing.

i.e. I want to say following scenatrio:
1.Initiated 2. Calling (Server send push notification and waiting for push result) 3. Ringing  (when push successful) 4. no-answer

I don't know but why above case was not implemented ?

**Comment by bobiechen-twilio** [comment]
Hi @girubhai 

Twilio does receive the result response when sending the notification requests to Apple APN service, but does not receive further notice if the notification has been properly received by the mobile client, which means it's hard for the Twilio Voice service to only notify the caller client a ringing event when the notification has reached to the client and the a incoming call notification is displayed.

Hope this answers your question.

Since there isn't an issue regarding the Node sample code, I'll close this issue. For any Programmable Voice (SDK) related questions, you are welcome to open new tickets in [the twilio-voice-ios repository](https://github.com/twilio/twilio-voice-ios).

Cheers,
-bobie
